# Default values for Flotorch Helm chart

# Global settings
global:
  # Domains
  consoleDomain: "console.flotorch.com"
  gatewayDomain: gateway.flotorch.com
  
  # Image registry
  imageRegistry: 677276078734.dkr.ecr.us-east-1.amazonaws.com

# Redis configuration
redis:
  image:
    repository: redis
    tag: 7.4.2-alpine3.21
  persistence:
    enabled: true
    size: 1Gi

# ClickHouse configuration
clickhouse:
  image:
    repository: clickhouse
    tag: 25.2.2
  auth:
    username: flotorch
    password: ad59165b73960e4c9b3e5a58ababad07
  persistence:
    dataSize: 10Gi
    logsSize: 2Gi

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: 17.4
  auth:
    username: postgres
    password: u6RLCfL9AJBYvkfB
    database: flotorch
  persistence:
    enabled: true
    size: 5Gi

# Console configuration
console:
  image:
    repository: flotorch/console
    tag: 162
  # These values can be overridden during deployment
  domain: "console.flotorch.com"
  sessionPassword: h3dPidJQENDRR5RrzL8SMRPGGaeFdEC8
  encryptionKey: GXQA5xxSYm38c37zaDnE4gCd9MBJhfDX
  pairingKey: iazRs8LdRkYS7nmxRrqqbrtXShrDdFEe
  experimentation:
    host: "https://tpm7t72ern.us-east-1.awsapprunner.com/api"
    username: "admin"
    password: "Flotorch@123"
  service:
    port: 3000
    targetPort: 3000

# Gateway configuration
gateway:
  image:
    repository: flotorch/gateway
    tag: 12
  name: prod-gateway
  service:
    port: 3000
    targetPort: 3000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  hosts:
    console:
      host: console.flotorch.com
      paths:
        - path: /
          pathType: Prefix
    gateway:
      host: gateway.flotorch.com
      paths:
        - path: /
          pathType: Prefix
