{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flotorch-console-ingress
  labels:
    app: console
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.hosts.console.host }}
    http:
      paths:
      {{- range .Values.ingress.hosts.console.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: console
            port:
              number: {{ $.Values.console.service.port }}
      {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flotorch-gateway-ingress
  labels:
    app: gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.hosts.gateway.host }}
    http:
      paths:
      {{- range .Values.ingress.hosts.gateway.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: gateway
            port:
              number: {{ $.Values.gateway.service.port }}
      {{- end }}
{{- end }}
